### ISSUE TITLE
Исправить работу алгоритма

### ISSUE THREAD

**Issue by Kasiwadzaki** [gunhs/PeacockTeam#3]
Добрый день, меня зовут Вадим, я разработчик компании Uno-Soft.

В текущем репе предоставлен закоментированный код(видимо во время локальных тестов не глядя залили). Я расоментировал и протестировал. Результат:
1. На файле https://github.com/PeacockTeam/new-job/blob/master/lng.7z ответ количества групп неверный
2. На файле https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z с ограничением по памяти в 1G ошибка OutOfMemoryError

**Comment by gunhs** [comment]
Добрый день.
Код оптимизировал. Теперь ошибки быть не должно.
Добавил проверку валидности строк (сильно влияет на производительность, но не на результат для текущих входных данных). Добавил проверку, что группа должна состоять из более, чем одного элемента.
